## Use vectorised numpy operations to achieve what you're trying to do in 2 steps...

#### Step 1 will get the column means, and step 2 will replace the null values with means

__STEP 1__<br\>
colmean = np.nanmean([your numpy array], axis = 0)<br\>

__STEP 2__<br\>
[your numpy array][np.where(np.isnan(your array))]=np.take(colmean,np.where(np.isnan(your array))[1])

I realise this chaining may seem like a mouthful to swallow. Let's break it up then...

I've included all the steps so that you can recreate it...

In [1]:
import numpy as np

In [56]:
temp = np.arange(20).reshape(4,5)
temp

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [57]:
# since we want to play with null values, let's convert the whole array into float

temp = temp.astype(float)
temp

array([[  0.,   1.,   2.,   3.,   4.],
       [  5.,   6.,   7.,   8.,   9.],
       [ 10.,  11.,  12.,  13.,  14.],
       [ 15.,  16.,  17.,  18.,  19.]])

In [58]:
# now, let's remove data from a couple of cells in order to create your situation

temp[2,1] = np.nan
temp[0,2] = np.nan
temp[1,2] = np.nan
temp[2,2] = np.nan
temp

array([[  0.,   1.,  nan,   3.,   4.],
       [  5.,   6.,  nan,   8.,   9.],
       [ 10.,  nan,  nan,  13.,  14.],
       [ 15.,  16.,  17.,  18.,  19.]])

In [59]:
# you can get creative in the ways in which you can access a numpy array!
temp[1:-1,1:-1]

array([[  6.,  nan,   8.],
       [ nan,  nan,  13.]])

In [60]:
# the numpy method nanmean will give you the column means (if axis = 0) is used by ignoring the nans
colmean = np.nanmean(temp, axis = 0)
colmean

array([  7.5       ,   7.66666667,  17.        ,  10.5       ,  11.5       ])

In [63]:
# get the indicies in the array that you need to replace with the column means
indices = np.where(np.isnan(temp))
indices

(array([0, 1, 2, 2], dtype=int64), array([2, 2, 1, 2], dtype=int64))

In [64]:
#insert the column means in the indices. the take method is used to align the arrays
temp[indices]=np.take(colmean,indices[1])

# finally!
temp

array([[  0.        ,   1.        ,  17.        ,   3.        ,   4.        ],
       [  5.        ,   6.        ,  17.        ,   8.        ,   9.        ],
       [ 10.        ,   7.66666667,  17.        ,  13.        ,  14.        ],
       [ 15.        ,  16.        ,  17.        ,  18.        ,  19.        ]])

## Even better, I suggest doing this using the power and elegance of pandas!

### By using pandas, we can replace your requirement with one line of code: <br\>
__[your dataframe].fillna(dataframe.mean(), inplace = True__

## Here's whats happening under the hood...

In [16]:
# make sure you've downloaded like how we did it last week for the word cloud - pip install pandas

#import the pandas module
import pandas as pd

# create a dataframe for testing
np.random.seed(1)
temp = pd.concat((pd.DataFrame({'labels':['a','b','c','d']}),
                pd.DataFrame(np.random.randint(0,100,(4,3)),columns=list('XYZ'))
                ),axis = 1)
temp

labels   X   Y   Z
0      a  37  12  72
1      b   9  75   5
2      c  79  64  16
3      d   1  76  71

In [19]:
# now, let's remove data from a couple of cells in order to create your situation
# notice iloc is the pandas construct for finding the integer location of the dataframe element

temp.iloc[2,1] = np.nan
temp.iloc[0,2] = np.nan
temp.iloc[1,3] = np.nan
temp.iloc[2,3] = np.nan
temp

labels     X     Y     Z
0      a  37.0   NaN  72.0
1      b   9.0  75.0   NaN
2      c   NaN  64.0   NaN
3      d   1.0  76.0  71.0

In [26]:
# let's compute the means for all the columns. Notice the power of using numpy operations

print "mean calculated using numpy operations. Note: pandas uses numpy for statistical operations"
print temp.mean()
print "\n"

# calculate manually
print "Calculating manually..."
print "Mean(X) = ",(37.0+9+1)/3
print "Mean(Y) = ",(75.0+64+76)/3
print "Mean(Z) = ",(72.0+71)/2

mean calculated using numpy operations. Note: pandas uses numpy for statistical operations
X    15.666667
Y    71.666667
Z    71.500000
dtype: float64


Calculating manually...
Mean(X) =  15.6666666667
Mean(Y) =  71.6666666667
Mean(Z) =  71.5


In [27]:
# now, filling it all in.
temp.fillna(temp.mean(), inplace = True)
# THATS IT!

temp

labels          X          Y     Z
0      a  37.000000  71.666667  72.0
1      b   9.000000  75.000000  71.5
2      c  15.666667  64.000000  71.5
3      d   1.000000  76.000000  71.0